force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <description>Which holds data of student information</description>
    <label>Student</label>
    <nameField>
        <displayFormat>STU-{0000}</displayFormat>
        <label>Roll Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <label>First Name</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <label>Last Name</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>Password</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/StudentLoginController.cls
/*
Author: Bala Surendra Vallipalli
Date  : 05-05-24
*/
public without sharing class StudentLoginController {

    @AuraEnabled(cacheable=true)
    public static Student__c authenticateStudent(String rollNumber,String email,String passwordValue){
        List<Student__c> studentData=[SELECT Id,Name,Password__c, Email__c,First_Name__c, Last_Name__c  FROM Student__c
                           WHERE Name=:rollNumber AND Email__c =:email AND Password__c=:passwordValue];
        
        
        return studentData[0];
    }

}